name: Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: ${{matrix.os}}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOs-latest]
    # permissions:
    #   contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: permissions to use gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

    name: Build & push Docker image
    - uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: anshumanshukla46/cicd-check
        registry: docker.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
