name: Manually Build and Push Docker Image

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'  # You can customize this input to choose the tag

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout main branch
        with:
          ref: main  # Ensures it checks out the latest code from the main branch

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: anshumanshukla46/cicd-check:${{ github.event.inputs.image_tag }}  # Tag based on input (e.g., latest)
